Run: Run 1
     Default Description: Yes
     Log File: Run_1.log
     DSS File: Run_1.dss
     Is Save Spatial Results: No
     Last Modified Date: 1 September 2026
     Last Modified Time: 07:25:33
     Last Execution Date: 1 September 2026
     Last Execution Time: 07:26:01
     Basin: Basin 1
     Precip: Met 1
     Control: Control 1
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

